### PR TITLE
Milestone 1: Project setup

### PR DESCRIPTION
**Pull request by Luzaks**
First Milestone for tic-tact-toe project.

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @Luzaks and @mcastorena0316,

### Great job thus far guys, :raised_hands: just one suggestion to wrap this up.

- [x] Add the `.idea` folder to `.gitignore` and delete it from this repo.

**Kindly submit for another code review once this has been done.** _Happy coding!_ :tada:

**Review by ebukaume — COMMENTED** [review]
## Changes Required! :stop_sign: 

Hi @Luzaks 

Are you working on this alone? We are yet to see any commit from your partner.

Also, I am unable to run your main.rb file. Did you follow the instruction correctly?

review-oop-1

**Kindly submit another code review request after setting the right permissions on `bin/main.rb`**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by mcastorena0316** [comment]
hi @ebukaume we are actually doing it together, in fact i tried to run main.rb in my bash and it worked, since it was a small project, we finish it on the first drive. I would do the corrections.

**Comment by ebukaume** [comment]
> hi @ebukaume we are actually doing it together, in fact i tried to run main.rb in my bash and it worked, since it was a small project, we finish it on the first drive. I would do the corrections.

Okay. After making the corrections, your partner can clone the repo and test that it works before submitting another review.

Happy Coding!

**Comment by shshamim63** [comment]
## Status [:Approved:] :tada:
___
Hi @Luzaks  and @mcastorena0316  :wave: ,
You have successfully completed the first milestone. Best of luck for your next milestone.
### This :+1: is from me, you can merge it.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Pull request merged**
